FROM mcr.microsoft.com/dotnet/core/aspnet:3.0

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

EXPOSE 5000

ENV TZ=Europe/Brussels
ENV CONNECTION_STRING=...
ENV ARENA_SIZE=...
ENV VALIDATION_HOST=...
ENV BOT_DEPLOYMENT_LIMIT=1

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Web.Api.dll"]