FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.0-alpine3.8

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

EXPOSE 5000

ENV TZ=Europe/Brussels
ENV CONNECTION_STRING=...
ENV ARENA_SIZE=...

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Web.Api.dll"]