FROM mcr.microsoft.com/dotnet/runtime:5.0

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

ENV TZ=Europe/Brussels
ENV CONNECTION_STRING=...
ENV ARENA_SIZE=...
ENV ELASTIC_HOST=...

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Processor.dll"]