FROM mcr.microsoft.com/dotnet/core/runtime:3.1

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

ENV TZ=Europe/Brussels
ENV CONNECTION_STRING=...
ENV ARENA_SIZE=...

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Processor.dll"]