FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

ENV TZ=Europe/Brussels
ENV CERTIFICATE_FILENAME=...
ENV CERTIFICATE_PASSWORD=...

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Validator.dll"]