FROM mcr.microsoft.com/dotnet/core/sdk:3.0-bionic

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

ENV TZ=Europe/Brussels
ENV CONNECTION_STRING=...
ENV ARENA_SIZE=...

# Start the app
ENTRYPOINT CSharpWars.ScriptProcessor.exe